version: '3.8'
services:
  manager:
    image: docker:dind
    container_name: manager
    privileged: true
    ports:
      - "8081:5000"
      - "8082:8080"
      - "8085:8085"
      - "8086:8086"
    volumes:
      - .:/project
    networks:
      swarm-network:
        ipv4_address: 172.20.0.10

  worker-1:
    image: docker:dind
    container_name: worker-1
    privileged: true
    volumes:
      - .:/project 
    networks:
      swarm-network:
        ipv4_address: 172.20.0.11

  worker-2:
    image: docker:dind
    container_name: worker-2
    privileged: true
    volumes:
      - .:/project 
    networks:
      swarm-network:
        ipv4_address: 172.20.0.12

networks:
  swarm-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16